# -*- coding: utf-8 -*-
"""analisis_estadistico_OE9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oGoe1gNzOlYgRGAdzhsFQuSVJ6L2z_Li

# Análisis estadístico OE9 — TerraRover-Gen

Este notebook ejecuta el análisis estadístico completo del OE9 (Robustez física).

**Instrucciones de uso en Google Colab:**
1. Sube los 12 archivos CSV al área de archivos del notebook (icono de carpeta a la izquierda):
   - 6 del agente RL: baseline V3 (`HuskyAgent2_metricas_V3_F3_02.csv`), baseline BumpyGround (`HuskyAgent2_metricas_BumpyGround.csv`), Sticky V3 (`HuskyAgent2_metricas_TerrainSticky_V3_F3_02.csv`), Sticky BumpyGround (`HuskyAgent2_metricas_TerrainSticky_BumpyGround.csv`), FL2000 V3 (`HuskyAgent2_metricas_FL2000_V3_F3_02.csv`), FL2000 BumpyGround (`HuskyAgent2_metricas_FL2000_BumpyGround.csv`).
   - 6 del heurístico: análogos con prefijo `HuskyHeuristic_metricas_`.
2. Ejecuta las celdas de arriba abajo (Shift+Enter).
3. Los resultados se imprimen en la salida y se guardan en `resultados_OE9.json`.

## 1. Dependencias
"""

!pip install statsmodels --quiet

"""## 2. Imports y configuración"""

import os
import json
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar
from statsmodels.stats.proportion import proportion_confint

CSV_DIR = '.'

FILES = {
    ('RL',  'V3',           'baseline'): 'HuskyAgent2_metricas_V3_F3_02.csv',
    ('RL',  'V3',           'sticky'):   'HuskyAgent2_metricas_TerrainSticky_V3_F3_02.csv',
    ('RL',  'V3',           'fl2000'):   'HuskyAgent2_metricas_FL2000_V3_F3_02.csv',
    ('RL',  'BumpyGround',  'baseline'): 'HuskyAgent2_metricas_BumpyGround.csv',
    ('RL',  'BumpyGround',  'sticky'):   'HuskyAgent2_metricas_TerrainSticky_BumpyGround.csv',
    ('RL',  'BumpyGround',  'fl2000'):   'HuskyAgent2_metricas_FL2000_BumpyGround.csv',
    ('HEU', 'V3',           'baseline'): 'HuskyHeuristic_metricas_V3_F3_02.csv',
    ('HEU', 'V3',           'sticky'):   'HuskyHeuristic_metricas_TerrainSticky_V3_F3_02.csv',
    ('HEU', 'V3',           'fl2000'):   'HuskyHeuristic_metricas_FL2000_V3_F3_02.csv',
    ('HEU', 'BumpyGround',  'baseline'): 'HuskyHeuristic_metricas_BumpyGround.csv',
    ('HEU', 'BumpyGround',  'sticky'):   'HuskyHeuristic_metricas_TerrainSticky_BumpyGround.csv',
    ('HEU', 'BumpyGround',  'fl2000'):   'HuskyHeuristic_metricas_FL2000_BumpyGround.csv',
}

CONFIG_LABEL = {
    'baseline': 'μ=0.3, FL=1000 (baseline)',
    'sticky':   'μ=1.5, FL=1000 (fricción alta)',
    'fl2000':   'μ=0.3, FL=2000 (par alto)',
}

"""## 3. Funciones de análisis"""

def load(system, terrain, config):
    fname = FILES[(system, terrain, config)]
    df = pd.read_csv(os.path.join(CSV_DIR, fname), sep=';')
    return df.set_index('episodio').sort_index()

def align(df_a, df_b):
    common = df_a.index.intersection(df_b.index)
    return df_a.loc[common], df_b.loc[common]

def wilson_ci(successes, n, alpha=0.05):
    if n == 0: return 0.0, 0.0
    lo, hi = proportion_confint(successes, n, alpha=alpha, method='wilson')
    return lo*100, hi*100

def mcnemar_paired(succ_a, succ_b):
    a = int(((succ_a)&(succ_b)).sum())
    b = int(((~succ_a)&(succ_b)).sum())
    c = int((succ_a&(~succ_b)).sum())
    d = int((~succ_a&(~succ_b)).sum())
    if b+c == 0: return a, b, c, d, 1.0
    result = mcnemar([[a,b],[c,d]], exact=True)
    return a, b, c, d, float(result.pvalue)

def diff_props_paired_ci(b, c, n):
    if n == 0: return 0.0, 0.0, 0.0
    diff = (c-b)/n*100
    if b+c == 0: return diff, diff, diff
    se = np.sqrt((b+c-(c-b)**2/n)/n)/n
    return diff, ((c-b)/n - 1.96*se)*100, ((c-b)/n + 1.96*se)*100

def wilcoxon_paired(a, b):
    a, b = np.asarray(a), np.asarray(b)
    if (a-b == 0).all(): return None
    try: _, p = stats.wilcoxon(a, b, zero_method='wilcox', alternative='two-sided')
    except ValueError: return None
    n = len(a)
    z = stats.norm.ppf(1-p/2)
    return {'p': float(p), 'r': float(abs(z)/np.sqrt(n)),
            'median_a': float(np.median(a)), 'median_b': float(np.median(b)), 'n': int(n)}

def print_header(title, char='='):
    bar = char*90
    print(f'\n{bar}\n{title}\n{bar}')

"""## 4. Bloque A — Intra-sistema (baseline vs perturbado, mismo agente)

Para cada (sistema, terreno, perturbación) se compara el rendimiento del MISMO sistema en baseline vs perturbado bajo seeds compartidas.
"""

results = {'A_intra': {}, 'B_inter': {}, 'C_paired_clean': {}}

def analyze_intra(system, terrain, pert):
    label = CONFIG_LABEL[pert]
    print_header(f'{system} en {terrain}: baseline vs {label}', char='-')
    base = load(system, terrain, 'baseline')
    p = load(system, terrain, pert)
    base, p = align(base, p)
    n = len(base)
    sb = (base['resultado']=='SUCCESS').values
    sp = (p['resultado']=='SUCCESS').values
    nb, np_ = int(sb.sum()), int(sp.sum())
    lo_b, hi_b = wilson_ci(nb, n)
    lo_p, hi_p = wilson_ci(np_, n)
    print(f'Baseline:   {nb/n*100:5.1f}%  IC95% [{lo_b:5.1f}, {hi_b:5.1f}]  ({nb}/{n})')
    print(f'Perturbado: {np_/n*100:5.1f}%  IC95% [{lo_p:5.1f}, {hi_p:5.1f}]  ({np_}/{n})')
    print(f'\nDistribución (Baseline → Perturbado):')
    for r in ['SUCCESS', 'STUCK', 'COLLISION', 'FALL', 'SPIN']:
        cb, cp = int((base['resultado']==r).sum()), int((p['resultado']==r).sum())
        print(f'  {r:12s}: {cb:3d} → {cp:3d} ({cp-cb:+d})')
    a, b, c, d, pv = mcnemar_paired(sb, sp)
    diff = (np_-nb)/n*100
    _, dlo, dhi = diff_props_paired_ci(c, b, n)
    print(f'\nMcNemar pareado: p={pv:.4f} (a={a}, b={b}, c={c}, d={d})')
    print(f'Δ pert-base: {diff:+.1f}pp  IC95%: [{dlo:+.1f}, {dhi:+.1f}]')
    both = sb & sp
    nboth = int(both.sum())
    print(f'\nWilcoxon (n={nboth}):')
    if nboth >= 5:
        for var in ['pasos','tiempo_s','distancia_final_m','energia_total']:
            res = wilcoxon_paired(base.loc[both,var], p.loc[both,var])
            if res is None:
                print(f'  {var:24s}: no calculable')
            else:
                d_str = 'base<pert' if res['median_a']<res['median_b'] else 'base>pert'
                print(f'  {var:24s}: base={res["median_a"]:8.2f} pert={res["median_b"]:8.2f} ({d_str}) p={res["p"]:.4f} r={res["r"]:.3f}')
    return {'n':n,'baseline_rate':nb/n*100,'perturbed_rate':np_/n*100,
            'mcnemar_p':pv,'diff_pp':diff,'diff_ci':(dlo,dhi),
            'results_baseline':dict(base['resultado'].value_counts()),
            'results_perturbed':dict(p['resultado'].value_counts())}

for system in ['RL', 'HEU']:
    for terrain in ['V3', 'BumpyGround']:
        for pert in ['sticky', 'fl2000']:
            results['A_intra'][f'{system}_{terrain}_{pert}'] = analyze_intra(system, terrain, pert)

"""## 5. Bloque B — Inter-sistema (RL vs HEU bajo cada configuración)"""

def analyze_inter(terrain, config):
    label = CONFIG_LABEL[config]
    print_header(f'RL vs HEU en {terrain} con {label}', char='-')
    rl = load('RL', terrain, config)
    heu = load('HEU', terrain, config)
    rl, heu = align(rl, heu)
    n = len(rl)
    sr = (rl['resultado']=='SUCCESS').values
    sh = (heu['resultado']=='SUCCESS').values
    nr, nh = int(sr.sum()), int(sh.sum())
    lo_r, hi_r = wilson_ci(nr, n)
    lo_h, hi_h = wilson_ci(nh, n)
    print(f'RL:  {nr/n*100:5.1f}%  IC95% [{lo_r:5.1f}, {hi_r:5.1f}]  ({nr}/{n})')
    print(f'HEU: {nh/n*100:5.1f}%  IC95% [{lo_h:5.1f}, {hi_h:5.1f}]  ({nh}/{n})')
    a, b, c, d, pv = mcnemar_paired(sr, sh)
    diff = (nr-nh)/n*100
    _, dlo, dhi = diff_props_paired_ci(b, c, n)
    print(f'\nMcNemar pareado RL vs HEU: p={pv:.4f}')
    print(f'Tabla 2×2: ambos+={a}, HEU+/RL-={b}, RL+/HEU-={c}, ambos-={d}')
    print(f'Δ RL-HEU: {diff:+.1f}pp  IC95%: [{dlo:+.1f}, {dhi:+.1f}]')
    # Wilcoxon pareado en SUCCESS común
    both = sr & sh
    nboth = int(both.sum())
    print(f'\nWilcoxon pareado en SUCCESS común (n={nboth}):')
    wilcox = {}
    if nboth >= 5:
        for var in ['pasos','tiempo_s','distancia_final_m','energia_total']:
            res = wilcoxon_paired(rl.loc[both,var], heu.loc[both,var])
            if res is None:
                print(f'  {var:24s}: no calculable')
                wilcox[var] = None
            else:
                d_str = 'RL<HEU' if res['median_a']<res['median_b'] else 'RL>HEU'
                print(f'  {var:24s}: RL={res["median_a"]:8.2f} HEU={res["median_b"]:8.2f} ({d_str}) p={res["p"]:.4f} r={res["r"]:.3f}')
                wilcox[var] = res
    else:
        print(f'  (insuficientes pares con SUCCESS común)')
    return {'n':n,'rl_rate':nr/n*100,'heu_rate':nh/n*100,
            'mcnemar_p':pv,'diff_pp':diff,'diff_ci':(dlo,dhi),
            'n_both_success':nboth,'wilcoxon':wilcox}

for terrain in ['V3', 'BumpyGround']:
    for config in ['baseline', 'sticky', 'fl2000']:
        results['B_inter'][f'{terrain}_{config}'] = analyze_inter(terrain, config)

"""## 6. Bloque C — Análisis pareado limpio en BumpyGround

Excluye seeds donde cualquiera de los dos sistemas tuvo FALL (limpieza simétrica).
"""

def analyze_clean(config):
    label = CONFIG_LABEL[config]
    print_header(f'Análisis pareado limpio: RL vs HEU en BumpyGround con {label}', char='-')
    rl = load('RL', 'BumpyGround', config)
    heu = load('HEU', 'BumpyGround', config)
    rl, heu = align(rl, heu)
    n_orig = len(rl)
    fall_rl = (rl['resultado']=='FALL').values
    fall_heu = (heu['resultado']=='FALL').values
    excl = fall_rl | fall_heu
    keep = ~excl
    n_excl = int(excl.sum())
    n = int(keep.sum())
    rl_c, heu_c = rl.iloc[keep], heu.iloc[keep]
    print(f'Excluidos: {n_excl} | Brutos: {n_orig} → Válidos: {n}\n')
    sr = (rl_c['resultado']=='SUCCESS').values
    sh = (heu_c['resultado']=='SUCCESS').values
    nr, nh = int(sr.sum()), int(sh.sum())
    lo_r, hi_r = wilson_ci(nr, n)
    lo_h, hi_h = wilson_ci(nh, n)
    print(f'RL:  {nr/n*100:5.1f}%  IC95% [{lo_r:5.1f}, {hi_r:5.1f}]  ({nr}/{n})')
    print(f'HEU: {nh/n*100:5.1f}%  IC95% [{lo_h:5.1f}, {hi_h:5.1f}]  ({nh}/{n})')
    print(f'\nDistribución sobre conjunto limpio:')
    for r in ['SUCCESS', 'STUCK', 'COLLISION', 'FALL', 'SPIN']:
        cr = int((rl_c['resultado']==r).sum())
        ch = int((heu_c['resultado']==r).sum())
        print(f'  {r:12s}: RL={cr:3d}  HEU={ch:3d}')
    a, b, c, d, pv = mcnemar_paired(sr, sh)
    diff = (nr-nh)/n*100
    _, dlo, dhi = diff_props_paired_ci(b, c, n)
    print(f'\nMcNemar pareado RL vs HEU (limpio): p={pv:.4f}')
    print(f'Δ RL-HEU: {diff:+.1f}pp  IC95%: [{dlo:+.1f}, {dhi:+.1f}]')
    # Wilcoxon pareado en SUCCESS común sobre conjunto limpio
    both = sr & sh
    nboth = int(both.sum())
    print(f'\nWilcoxon pareado en SUCCESS común (n={nboth}):')
    wilcox = {}
    if nboth >= 5:
        for var in ['pasos','tiempo_s','distancia_final_m','energia_total']:
            res = wilcoxon_paired(rl_c.loc[both,var], heu_c.loc[both,var])
            if res is None:
                print(f'  {var:24s}: no calculable')
                wilcox[var] = None
            else:
                d_str = 'RL<HEU' if res['median_a']<res['median_b'] else 'RL>HEU'
                print(f'  {var:24s}: RL={res["median_a"]:8.2f} HEU={res["median_b"]:8.2f} ({d_str}) p={res["p"]:.4f} r={res["r"]:.3f}')
                wilcox[var] = res
    else:
        print(f'  (insuficientes pares con SUCCESS común)')
    return {'n_orig':n_orig,'n_excluded':n_excl,'n':n,
            'rl_rate':nr/n*100,'heu_rate':nh/n*100,
            'mcnemar_p':pv,'diff_pp':diff,'diff_ci':(dlo,dhi),
            'n_both_success':nboth,'wilcoxon':wilcox,
            'results_rl_clean':dict(rl_c['resultado'].value_counts()),
            'results_heu_clean':dict(heu_c['resultado'].value_counts())}

for config in ['sticky', 'fl2000']:
    results['C_paired_clean'][f'BumpyGround_{config}_clean'] = analyze_clean(config)

"""## 7. Tabla resumen y exportación"""

print_header('TABLA RESUMEN — Tasas de éxito y p-valores McNemar')
print(f'\n{"Comparación":50s} {"Δ pp":>8s} {"p McNemar":>12s}')
print('-' * 75)
print('\nA. Intra-sistema (baseline vs perturbado):')
for key, d in results['A_intra'].items():
    print(f'  {key:48s} {d["diff_pp"]:>+7.1f}  {d["mcnemar_p"]:>11.4f}')
print('\nB. Inter-sistema (RL vs HEU):')
for key, d in results['B_inter'].items():
    print(f'  {key:48s} {d["diff_pp"]:>+7.1f}  {d["mcnemar_p"]:>11.4f}')
print('\nC. Pareado limpio en BumpyGround:')
for key, d in results['C_paired_clean'].items():
    print(f'  {key:48s} {d["diff_pp"]:>+7.1f}  {d["mcnemar_p"]:>11.4f}')

def make_serializable(obj):
    if isinstance(obj, dict): return {k: make_serializable(v) for k,v in obj.items()}
    if isinstance(obj, (list,tuple)): return [make_serializable(v) for v in obj]
    if isinstance(obj, (np.integer,)): return int(obj)
    if isinstance(obj, (np.floating,)): return float(obj)
    if isinstance(obj, np.bool_): return bool(obj)
    return obj

with open('resultados_OE9.json', 'w', encoding='utf-8') as f:
    json.dump(make_serializable(results), f, indent=2, ensure_ascii=False)
print('\nResultados guardados en resultados_OE9.json')